.TH sskk 6 "2021-07-21" "sskk a2"
.SH NAME
sskk - linguistic terminal game
.SH SYNOPSIS
.B sskk
.SH DESCRIPTION
.B sskk
is a lingusitic terminal game. The game is heavily inspired by nethack(6). The
game's controls and display are intended to be as easy to learn as possible.
.SH TUTORIAL
The most basic of commands is moving around. This can be done with hjkl.
You can identify something on the screen through ';'.
.SH OPTIONS
None yet.
.SH BUGS
None that I know of. Yet.
.SH AUTHOR
kaye (kittycatfangz@gmail.com)
.SH SEE ALSO
nethack(6), atc(6)
