.TH sskk_lang 7 "2021-08-26" "sskk language"
.SH NAME
sskk_lang - the language from sskk (spoilers!)
.SH GRAMMAR
sskk_lang is head-final (for example, it uses SOV word order)
.SH NOUNS
anak - key (from Manchu "anakū")

isik - door (from Uyghur "ishik")
.SH VERBS
wan - open (from reconstructed Old/Middle Egyptian "wn")

ei - [negative verb] (from Finnish "ei")

pai - press (from Finnish "paina")
